import { Course } from "../../types/course";

export const courses: Course[] = [
  {
    id: 1,
    title: "Introdução à Programação",
    description: "Aprenda o básico da programação usando Python.",
    startDate: "2024-07-01",
    endDate: "2024-08-12",
    urls: [{ id: 1, url: "https://www.youtube.com/watch?v=4p7axLXXBGU" }],
  },
  {
    id: 2,
    title: "JavaScript Avançado",
    description: "Domine conceitos e técnicas avançadas de JavaScript.",
    startDate: "2024-08-04",
    endDate: "2024-08-20",
    urls: [
      { id: 1, url: "https://www.youtube.com/watch?v=RvcRxEeJqi8" },
      { id: 2, url: "https://www.youtube.com/watch?v=VYDCS_JkhLY" },
    ],
  },
  {
    id: 3,
    title: "Bootcamp de Desenvolvimento Web",
    description: "Um guia completo para se tornar um desenvolvedor web.",
    startDate: "2024-08-10",
    endDate: "2024-08-18",
    urls: [{ id: 1, url: "https://www.youtube.com/watch?v=zJSY8tbf_ys" }],
  },
  {
    id: 4,
    title: "Fundamentos de Ciência de Dados",
    description: "Uma introdução à ciência de dados e aprendizado de máquina.",
    startDate: "2024-06-20",
    endDate: "2024-08-30",
    urls: [{ id: 1, url: "https://www.youtube.com/watch?v=bEs1OKnuSaA" }],
  },
  {
    id: 5,
    title: "Essenciais de Computação em Nuvem",
    description: "Entenda o básico de computação em nuvem com AWS.",
    startDate: "2024-07-05",
    endDate: "2024-08-14",
    urls: [{ id: 1, url: "https://www.youtube.com/watch?v=QW4gA18yGh0" }],
  },
  {
    id: 6,
    title: "Noções Básicas de Cibersegurança",
    description:
      "Aprenda como proteger sistemas e dados contra ameaças cibernéticas.",
    startDate: "2024-07-25",
    endDate: "2024-08-22",
    urls: [{ id: 1, url: "https://www.youtube.com/watch?v=yAHCyvXfLeA" }],
  },
  {
    id: 7,
    title: "Introdução à IA",
    description: "Explore os fundamentos da inteligência artificial.",
    startDate: "2024-06-01",
    endDate: "2024-08-10",
    urls: [{ id: 1, url: "https://www.youtube.com/watch?v=ucoFLlasfIo" }],
  },
  {
    id: 8,
    title: "Desenvolvimento de Aplicativos Móveis",
    description: "Construa aplicativos móveis usando Flutter.",
    startDate: "2024-04-15",
    endDate: "2024-08-09",
    urls: [{ id: 1, url: "https://www.youtube.com/watch?v=X-XfVvd41O8" }],
  },
  {
    id: 9,
    title: "Práticas de DevOps",
    description:
      "Implemente práticas de DevOps para melhor entrega de software.",
    startDate: "2024-06-10",
    endDate: "2024-08-28",
    urls: [{ id: 1, url: "https://www.youtube.com/watch?v=bwO8EZf0gLI" }],
  },
  {
    id: 10,
    title: "Gerenciamento de Banco de Dados",
    description:
      "Aprenda a projetar e gerenciar bancos de dados de forma eficaz.",
    startDate: "2024-05-20",
    endDate: "2024-08-11",
    urls: [{ id: 1, url: "https://www.youtube.com/watch?v=Ofktsne-utM" }],
  },
  {
    id: 11,
    title: "Gerenciamento Ágil de Projetos",
    description: "Gerencie projetos de forma eficaz usando metodologias ágeis.",
    startDate: "2024-07-01",
    endDate: "2024-08-25",
    urls: [{ id: 1, url: "https://www.youtube.com/watch?v=Ipjxv5uU1R8" }],
  },
  {
    id: 12,
    title: "Blockchain para Iniciantes",
    description: "Entenda os fundamentos da tecnologia blockchain.",
    startDate: "2024-05-01",
    endDate: "2024-08-07",
    urls: [{ id: 1, url: "https://www.youtube.com/watch?v=dkElPTevoR4" }],
  },
];
