import { Course } from "../../types/course";

export const courses: Course[] = [
  {
    id: 1,
    title: "Introdução à Programação",
    description: "Aprenda o básico da programação usando Python.",
    startDate: "2024-07-01",
    endDate: "2024-08-12",
    videos: ["video1.mp4", "video2.mp4"],
  },
  {
    id: 2,
    title: "JavaScript Avançado",
    description: "Domine conceitos e técnicas avançadas de JavaScript.",
    startDate: "2024-06-15",
    endDate: "2024-08-20",
    videos: ["video3.mp4", "video4.mp4"],
  },
  {
    id: 3,
    title: "Bootcamp de Desenvolvimento Web",
    description: "Um guia completo para se tornar um desenvolvedor web.",
    startDate: "2024-05-10",
    endDate: "2024-08-18",
    videos: ["video5.mp4", "video6.mp4", "video7.mp4"],
  },
  {
    id: 4,
    title: "Fundamentos de Ciência de Dados",
    description: "Uma introdução à ciência de dados e aprendizado de máquina.",
    startDate: "2024-06-20",
    endDate: "2024-08-30",
    videos: ["video8.mp4", "video9.mp4"],
  },
  {
    id: 5,
    title: "Essenciais de Computação em Nuvem",
    description: "Entenda o básico de computação em nuvem com AWS.",
    startDate: "2024-07-05",
    endDate: "2024-08-14",
    videos: ["video10.mp4"],
  },
  {
    id: 6,
    title: "Noções Básicas de Cibersegurança",
    description:
      "Aprenda como proteger sistemas e dados contra ameaças cibernéticas.",
    startDate: "2024-07-25",
    endDate: "2024-08-22",
    videos: ["video11.mp4", "video12.mp4"],
  },
  {
    id: 7,
    title: "Introdução à IA",
    description: "Explore os fundamentos da inteligência artificial.",
    startDate: "2024-06-01",
    endDate: "2024-08-10",
    videos: ["video13.mp4"],
  },
  {
    id: 8,
    title: "Desenvolvimento de Aplicativos Móveis",
    description: "Construa aplicativos móveis usando Flutter.",
    startDate: "2024-04-15",
    endDate: "2024-08-09",
    videos: ["video14.mp4", "video15.mp4"],
  },
  {
    id: 9,
    title: "Práticas de DevOps",
    description:
      "Implemente práticas de DevOps para melhor entrega de software.",
    startDate: "2024-06-10",
    endDate: "2024-08-28",
    videos: ["video16.mp4"],
  },
  {
    id: 10,
    title: "Gerenciamento de Banco de Dados",
    description:
      "Aprenda a projetar e gerenciar bancos de dados de forma eficaz.",
    startDate: "2024-05-20",
    endDate: "2024-08-11",
    videos: ["video17.mp4", "video18.mp4"],
  },
  {
    id: 11,
    title: "Gerenciamento Ágil de Projetos",
    description: "Gerencie projetos de forma eficaz usando metodologias ágeis.",
    startDate: "2024-07-01",
    endDate: "2024-08-25",
    videos: ["video19.mp4"],
  },
  {
    id: 12,
    title: "Blockchain para Iniciantes",
    description: "Entenda os fundamentos da tecnologia blockchain.",
    startDate: "2024-05-01",
    endDate: "2024-08-07",
    videos: ["video20.mp4"],
  },
];
